export const USER_LOGIN = "USER_LOGIN";
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_ALL_USER = "FETCH_ALL_USER";
export const FETCH_DATA = "FETCH_DATA";
export const FETCH_VISITORS = "FETCH_VISITORS";
export const FETCH_ALL_VISITORS = "FETCH_ALL_VISITORS";
export const FETCH_INVITEES = "FETCH_INVITEES";
export const FETCH_GUARDS = "FETCH_GUARDS";
export const FETCH_ADMINS = "FETCH_ADMINS";
export const FETCH_NOTICES = "FETCH_NOTICES";
export const FETCH_PARCELS = "FETCH_PARCELS";
export const FETCH_OFFICE = "FETCH_OFFICE";
export const FETCH_GUARD_PHONE = "FETCH_GUARD_PHONE";
export const FETCH_ALL_EMPLOYEE = "FETCH_ALL_EMPLOYEE";
export const FETCH_ALL_MAILS = "FETCH_ALL_MAILS";
export const FETCH_ADMIN_DATA = "FETCH_ADMIN_DATA";
export const FETCH_RECENT_VISITORS = "FETCH_RECENT_VISITORS";

export const FETCH_EMPLOYEE_REQUEST = "FETCH_EMPLOYEE_REQUEST";

export const CURRENT_TIME = "CURRENT_TIME";

export const ADD_EMPLOYEES = "ADD_EMPLOYEES";

export const ADD_STATUS = "ADD_STATUS";
export const DELETE_STATUS = "DELETE_STATUS";
export const UPDATE_STATUS = "UPDATE_STATUS";

export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";
export const NULL = "NULL";
